---
generic-service:
  nameOverride: hmpps-send-legal-mail-staff-ui
  productId: "DPS068"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-send-legal-mail-staff-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: check-rule39-mail-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  namespace_secrets:
    hmpps-send-legal-mail-staff-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    slmtp-staff-ui-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons
      - global_protect

generic-prometheus-alerts:
  targetApplication: hmpps-send-legal-mail-staff-ui
