---
# Per environment values which override defaults in hmpps-send-legal-mail-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: check-rule39-mail-dev.prison.service.justice.gov.uk
  env:
    INGRESS_URL: "https://check-rule39-mail-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-dev.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    ark-dom1-psn1: 51.247.4.0/24
    ark-dom1-psn2: 51.247.3.0/24
    ark-nps-hmcts-ttp1: 195.59.75.0/24
    ark-nps-hmcts-ttp2: 194.33.192.0/25
    ark-nps-hmcts-ttp3: 194.33.193.0/25
    ark-nps-hmcts-ttp4: 194.33.196.0/25
    ark-nps-hmcts-ttp5: 194.33.197.0/25
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    quantum1: 62.25.109.197/32
    quantum2: 212.137.36.230/32
    quantum3: 195.92.38.16/28
    moj-official-tgw-preprod: 51.149.251.0/24
    moj-official-tgw-prod: 51.149.250.0/24
    moj-official-ark-c-expo-e: 51.149.249.0/29
    moj-official-ark-c-vodafone: 194.33.248.0/29
    moj-official-ark-f-vodafone: 194.33.249.0/29
    moj-official-ark-f-expo-e: 51.149.249.32/29
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
