---
# Per environment values which override defaults in hmpps-send-legal-mail-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: check-rule39-mail-dev.prison.service.justice.gov.uk
  env:
    INGRESS_URL: "https://check-rule39-mail-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-dev.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: dev

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

  allowlist:
    moj-official-tgw-prod: 51.149.250.0/24
    groups:
      - internal

generic-prometheus-alerts:
  alertSeverity: hmpps-visits-send-legal-email-dev
