---
# Per environment values which override defaults in hmpps-send-legal-mail-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-send-legal-mail-staff-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-send-legal-mail-staff-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
