---
# Per environment values which override defaults in hmpps-send-legal-mail-staff-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-send-legal-mail-staff-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-send-legal-mail-staff-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-preprod.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
